sudo: false

language: java

jdk:
  - oraclejdk8
  - oraclejdk7
  - openjdk6

before_install:
  - sudo add-apt-repository ppa:cwchien/gradle -y
  - sudo apt-get update -q
  - sudo apt-get install gradle -y
  - gradle --version

before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start

notifications:
  irc:
    channels:
      - "chat.freenode.net#gral"
    on_success: change
    on_failure: always
    template:
      - "%{repository} (%{branch}:%{commit} by %{author}): %{message} (%{build_url})"
